# Generated by Django 5.1.1 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Добавьте новость и получите +15', max_length=150, verbose_name='Название')),
                ('anonce', models.CharField(default='Добавьте аннотацию к новости', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Здесь будет к примеру статья')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
